nome = input('Digite seu nome completo: ').strip()
print('Seu nome em maiusculo é: {}'.format(nome.upper()))
print('Seu nome em minusculo é: {}'.format(nome.lower()))
teste = nome.split()
teste = ''.join(teste)
print('Seu nome tem um total de {} letras'.format(len(teste)))
teste2 = nome.split()
print('Seu primeiro nome tem {} letras'.format(len(teste2[0])))